### ISSUE TITLE
DEPLOY ERROR

### ISSUE THREAD

**Issue by caioken00** [birdwell/Madden-Companion-Exporter#3]
hi,

i have this error when deploying into heroku:

2017-04-24T16:04:47.075379+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-04-24T16:04:47.075380+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-04-24T16:04:47.075380+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-04-24T16:04:47.075381+00:00 app[web.1]:     at Object.<anonymous> (/app/app.js:9:24)
2017-04-24T16:04:47.075382+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-04-24T16:04:47.075382+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-04-24T16:04:47.075381+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-04-24T16:04:47.075383+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-04-24T16:04:47.075384+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-04-24T16:04:47.161325+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-24T16:04:47.136633+00:00 heroku[web.1]: Process exited with status 1

PLS HELP!!!

**Comment by birdwell** [comment]
Do you mind sharing your repo of this project? You can email me at jbirdwell34@gmail.com

**Comment by cheeseheadnate** [comment]
I'll try to send it later tonight (4/28 ).

**Comment by birdwell** [comment]
Did you ever get this figured out?
